---
- project:
    check:
      jobs:
        - bosh-openstack-cpi-release-acceptance-test
        - bosh-openstack-cpi-release-acceptance-test-train
        - bosh-openstack-cpi-release-acceptance-test-stein
        - bosh-openstack-cpi-release-acceptance-test-rocky
        - bosh-openstack-cpi-release-acceptance-test-queens
        - bosh-openstack-cpi-release-acceptance-test-pike
        - bosh-openstack-cpi-release-acceptance-test-ocata

- job:
    name: bosh-openstack-cpi-release-acceptance-test
    parent: init-test
    description: |
      This job validation tests of bosh-openstack-cpi-release against OpenStack master branch
    run: .zuul/playbooks/bosh-openstack-cpi-release-acceptance-test/run.yaml

- job:
    name: bosh-openstack-cpi-release-acceptance-test-train
    parent: bosh-openstack-cpi-release-acceptance-test
    description: |
      This job validation tests of bosh-openstack-cpi-release against OpenStack Train release
    vars:
      global_env:
        OS_BRANCH: stable/train

- job:
    name: bosh-openstack-cpi-release-acceptance-test-stein
    parent: bosh-openstack-cpi-release-acceptance-test
    description: |
      This job validation tests of bosh-openstack-cpi-release against OpenStack Stein release
    vars:
      global_env:
        OS_BRANCH: stable/stein

- job:
    name: bosh-openstack-cpi-release-acceptance-test-rocky
    parent: bosh-openstack-cpi-release-acceptance-test
    description: |
      This job validation tests of bosh-openstack-cpi-release against OpenStack Rocky release
    vars:
      global_env:
        OS_BRANCH: stable/rocky

- job:
    name: bosh-openstack-cpi-release-acceptance-test-queens
    parent: bosh-openstack-cpi-release-acceptance-test
    description: |
      This job validation tests of bosh-openstack-cpi-release against OpenStack Queens release
    vars:
      global_env:
        OS_BRANCH: stable/queens

- job:
    name: bosh-openstack-cpi-release-acceptance-test-pike
    parent: bosh-openstack-cpi-release-acceptance-test
    description: |
      This job validation tests of bosh-openstack-cpi-release against OpenStack Pike release
    vars:
      global_env:
        OS_BRANCH: stable/pike

- job:
    name: bosh-openstack-cpi-release-acceptance-test-ocata
    parent: bosh-openstack-cpi-release-acceptance-test
    description: |
      This job validation tests of bosh-openstack-cpi-release against OpenStack Ocata release
    vars:
      global_env:
        OS_BRANCH: stable/ocata
