---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-openstack-cpi-release
  - name: version-semver
outputs:
  - name: candidate
run:
  path: bosh-openstack-cpi-release/ci/tasks/build-candidate.sh
