---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-openstack-cpi-release
  - name: terraform-cpi
  - name: bosh-director-deployment
run:
  path: bosh-openstack-cpi-release/ci/tasks/print_task_errors.sh
