---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-openstack-cpi-release
  - name: bosh-cpi-dev-artifacts
  - name: release-version-semver
outputs:
  - name: promote
run:
  path: bosh-openstack-cpi-release/ci/tasks/promote-candidate.sh
params:
  aws_access_key_id:     replace-me
  aws_secret_access_key: replace-me
  aws_assume_role_arn:   replace-me
