---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-openstack-cpi-release
  - name: lifecycle-log
outputs:
  - name: publish
run:
  path: bosh-openstack-cpi-release/ci/tasks/publish-api-calls.sh
params:
  publish_api_calls_enabled:  replace-me
