---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-openstack-cpi-release
  - name: stemcell
  - name: bats
  - name: terraform-cpi-deploy
  - name: bosh-director-deployment
outputs:
  - name: terraform-bats
run:
  path: bosh-openstack-cpi-release/ci/tasks/run-manual-networking-bats.sh
params:
  stemcell_name:                            replace-me
  openstack_flavor_with_ephemeral_disk:     replace-me
  openstack_flavor_with_no_ephemeral_disk:  replace-me
  bosh_vcap_password:                       replace-me
  availability_zone:                        replace-me
  bats_rspec_tags:                          ""
