---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: bosh-cpi-dev-artifacts
  - name: bosh-director-deployment
  - name: stemcell
  - name: bosh-release
  - name: version-semver
  - name: terraform-bats
run:
  path: bosh-cpi-src-in/ci/tasks/teardown-director.sh
