---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-openstack-cpi-release
outputs:
  - name: write-file
run:
  path: bosh-openstack-cpi-release/ci/tasks/write-ca-file.sh
params:
  file_content: replace-me
